using MediateX;
using Microsoft.Extensions.DependencyInjection;

// ============================================================================
// SPIKE: MediateX Source Generator Test
// This project tests that the source generator correctly discovers handlers
// and generates the AddMediateXGenerated() extension method.
// ============================================================================

Console.WriteLine("MediateX Source Generator Spike");
Console.WriteLine("================================\n");

// Setup DI container - Testing COEXISTENCE of both methods
var services = new ServiceCollection();

// METHOD 1: Source Generator registration (FAST - no reflection)
// This method is generated by MediateX.SourceGenerator
services.AddMediateXGenerated();

// METHOD 2: Reflection-based registration (for same handlers - simulates plugins)
// TryAdd in generated code prevents duplicate request handler registration
services.AddMediateX(cfg =>
{
    cfg.RegisterServicesFromAssemblyContaining<Program>();
});

Console.WriteLine("Both AddMediateXGenerated() and AddMediateX() coexist successfully!");

var provider = services.BuildServiceProvider();

// Test 1: Request/Response handler
Console.WriteLine("Test 1: Sending GetProductQuery...");
var mediator = provider.GetRequiredService<IMediator>();
var product = await mediator.Send(new GetProductQuery(42));
Console.WriteLine($"  Result: Product {{ Id = {product.Id}, Name = \"{product.Name}\" }}\n");

// Test 2: Void request handler
Console.WriteLine("Test 2: Sending DeleteProductCommand...");
await mediator.Send(new DeleteProductCommand(42));
Console.WriteLine("  Result: Command executed (void)\n");

// Test 3: Notification handlers
Console.WriteLine("Test 3: Publishing ProductCreatedNotification...");
await mediator.Publish(new ProductCreatedNotification(99, "New Product"));
Console.WriteLine();

Console.WriteLine("All tests passed! Source Generator is working.");

// ============================================================================
// Domain Models
// ============================================================================

public record Product(int Id, string Name);

// ============================================================================
// Requests & Handlers
// ============================================================================

// Request with response
public record GetProductQuery(int Id) : IRequest<Product>;

public class GetProductHandler : IRequestHandler<GetProductQuery, Product>
{
    public Task<Product> Handle(GetProductQuery request, CancellationToken cancellationToken)
    {
        Console.WriteLine($"  [GetProductHandler] Handling request for product {request.Id}");
        return Task.FromResult(new Product(request.Id, $"Product-{request.Id}"));
    }
}

// Void request (command)
public record DeleteProductCommand(int Id) : IRequest;

public class DeleteProductHandler : IRequestHandler<DeleteProductCommand>
{
    public Task Handle(DeleteProductCommand request, CancellationToken cancellationToken)
    {
        Console.WriteLine($"  [DeleteProductHandler] Deleting product {request.Id}");
        return Task.CompletedTask;
    }
}

// ============================================================================
// Notifications & Handlers
// ============================================================================

public record ProductCreatedNotification(int ProductId, string ProductName) : INotification;

public class ProductCreatedEmailHandler : INotificationHandler<ProductCreatedNotification>
{
    public Task Handle(ProductCreatedNotification notification, CancellationToken cancellationToken)
    {
        Console.WriteLine($"  [EmailHandler] Sending email for product: {notification.ProductName}");
        return Task.CompletedTask;
    }
}

public class ProductCreatedLogHandler : INotificationHandler<ProductCreatedNotification>
{
    public Task Handle(ProductCreatedNotification notification, CancellationToken cancellationToken)
    {
        Console.WriteLine($"  [LogHandler] Logging product created: {notification.ProductId}");
        return Task.CompletedTask;
    }
}
